<a href="https://colab.research.google.com/github/manhduc07/bai-tap/blob/master/bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [4]:
import numpy as np
m1 = np.arange(-15, 27, 0.7)
m1

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [5]:
m2 = np.random.normal(27, 1.2, 40)
m2

array([25.99190621, 25.42862361, 27.17329031, 27.35157785, 25.82697147,
       24.6022442 , 25.08562243, 26.35922619, 26.93975095, 26.47957331,
       27.09761661, 26.96374874, 27.17248393, 28.39463322, 27.90831336,
       26.53913789, 26.74772091, 27.22314029, 26.63711763, 25.46874657,
       26.35885584, 26.14054315, 25.92801881, 27.60563007, 28.05398859,
       27.81826713, 26.0326335 , 26.76258082, 27.67166072, 27.69317932,
       27.91099141, 28.86672911, 26.38621904, 27.65373902, 26.32126033,
       27.67058932, 27.79281519, 27.1732122 , 28.46374144, 26.19644415])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [6]:
m3 = np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17)
m3

array(['Britain', 'Viet Nam', 'Singapore', 'France', 'Viet Nam',
       'Britain', 'Singapore', 'France', 'France', 'Viet Nam', 'Viet Nam',
       'Britain', 'Singapore', 'Viet Nam', 'Viet Nam', 'Viet Nam',
       'France'], dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [7]:
m4 = np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 10, [0.1, 0.2, 0.1, 0.3, 0.4])
m4

array(['Singapore', 'Britain', 'Russia', 'Viet Nam', 'Britain', 'Britain',
       'France', 'France', 'Viet Nam', 'Britain'], dtype='<U9')

Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [8]:
from scipy import stats

#Sinh ngẫu nhiên mẫu theo phân phối chuẩn với mean = 5.5 std = 2.3 và size = 100
stats.norm.rvs(loc = 12.7, scale = 2.6, size = 30)

array([11.88617176, 11.62537443, 13.81350561, 17.29301034, 12.82119306,
       10.07744425, 12.95053922, 12.68541977, 12.99572533, 16.3133728 ,
       10.83254542, 12.90359482, 10.56197239, 14.71660305,  8.17284267,
       14.50832154,  8.18072308, 12.54364928, 14.47310638, 17.58269094,
       13.57360448, 13.94021799, 12.04385984, 13.7749485 , 14.12035186,
       10.05010785, 12.99124082, 11.88080665, 13.74897915, 10.4662626 ])

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [9]:
a = stats.poisson.rvs(mu=0.1, size=100)
j=0
for i in a:
  if i ==0:
    j+=1
print(j)

89
